import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers"

import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Vercel: Develop. Preview. Ship. For the best frontend teams',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar/>
          {children}
          <Footer/>
        </Providers>
        </body>
    </html>
  )
}
